on:
  push:
    tags:
      - '*'

name: VSCODE Extension Release
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - run: npm install
        continue-on-error: true
        
      - name: Debug GitHub Ref
        run: echo "github.ref is ${{ github.ref }}"

      - uses: lannonbr/vsce-action@master
        with:
          args: "package"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: generalizedtestmanager-*.vsix